# Generated by Django 6.0.3 on 2026-06-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_website', models.BooleanField(default=False)),
                ('has_ssl', models.BooleanField(default=False)),
                ('has_professional_email', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='leads.lead')),
            ],
        ),
    ]
