# Generated by Django 6.0.3 on 2026-06-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_multi_tenancy'),
        ('leads', '0002_auditresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('NOVO', 'Novo'), ('CONTATO', 'Contato'), ('NEGOCIACAO', 'Negociação'), ('FECHADO', 'Fechado'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_card', to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_cards', to='accounts.organization')),
            ],
        ),
    ]
