# Generated by Django 6.0.3 on 2026-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_multi_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='received_feedback_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
